phrases_list = [
    "El éxito del proyecto fue impresionante y dejó a todos motivados.",
    "La derrota fue devastadora, y causó mucha tristeza en el equipo.",
    "El ambiente fue tranquilo durante la presentación, con los presentadores motivados, pero la derrota al final dejó un sabor amargo.",
    "El servicio al cliente fue excelente, sin embargo, el producto era defectuoso.",
    "La noticia de su promoción fue recibida con gran alegría por sus colegas.",
    "El tráfico en la ciudad es terrible y estresante.",
    "La reunión fue productiva, pero el ambiente era tenso.",
    "Es un logro significativo, aunque algunos aspectos podrían mejorarse.",
    "La pérdida del contrato fue un golpe duro para la empresa.",
    "El ambiente en la oficina es neutral, ni muy bueno ni muy malo.",
    "La entrega del proyecto fue puntual y sin problemas.",
    "El comportamiento del cliente fue ofensivo e inaceptable.",
    "El clima de hoy es perfecto para un paseo al aire libre.",
    "El equipo trabajó de manera eficiente, pero la comunicación fue deficiente.",
    "El evento fue un desastre, nada salió como estaba planeado.",
]
